##############################################################################
#
#    Copyright (C) 2016 Exo Software, Lda. (<https://exosoftware.pt>)
#
##############################################################################
# pylint: disable=license-allowed, manifest-required-author

{
    "name": "Portugal - Payroll",
    "license": "OPL-1",
    "author": "Exo Software",
    "website": "https://github.com/exosoftware/portugal-payroll",
    "category": "Localization",
    "version": "19.0.9.1.1",
    "depends": [
        "ptplus",
        "ptplus_reports",
        "hr_holidays",
        "ptplus_partner",
        "hr_payroll_account",
        "hr_payroll_expense",
        "ptplus_expense",
    ],
    "data": [
        "data/hr_marital_status_pt.xml",
        "data/hr.income.tax.pt.csv",
        "data/hr_insurance_company_pt.xml",
        "data/hr.profession.pt.csv",
        "data/hr.qualification.pt.csv",
        "data/hr.social.security.tax.pt.csv",
        "data/hr_special_fiscal_regime_pt.xml",
        "data/ir_cron_data.xml",
        "data/hr_work_entry_data.xml",
        "data/ptplus_payroll_data.xml",
        "data/hr_holidays_data.xml",
        "report/hr_payroll_report.xml",
        "data/ptplus_payroll_rules.xml",
        "data/hr_rule_parameters_data.xml",
        "security/ir.model.access.csv",
        "security/ptplus_payroll_security.xml",
        "views/dataport_log_views.xml",
        "views/hr_employee_views.xml",
        "views/hr_income_tax_pt_views.xml",
        "views/hr_insurance_company_pt_views.xml",
        "views/hr_profession_pt_views.xml",
        "views/hr_qualification_pt_views.xml",
        "views/hr_social_security_tax_pt_views.xml",
        "views/res_partner_views.xml",
        "views/res_company_views.xml",
        "views/hr_professional_category_pt_views.xml",
        "views/hr_tax_office_pt_views.xml",
        "views/resource_calendar_views.xml",
        "views/hr_payroll_structure_views.xml",
        "views/hr_salary_complement_pt_views.xml",
        "views/menus.xml",
        "views/res_config_settings_views.xml",
        "views/hr_salary_rule_views.xml",
        "views/hr_payslip_views.xml",
        "views/email_template.xml",
        "views/employee_multiple_send_payslip.xml",
        "views/hr_employee_payroll_views.xml",
        "views/hr_allowance_provision_correction_views.xml",
        "report/report_payslip_templates.xml",
        "report/annual_income_stmt_report.xml",
        "report/payroll_dri_statement_report.xml",
        "wizards/payroll_statement.xml",
        "wizards/single_report_statement_views.xml",
        "wizards/l10n_pt_dmr_statement_wizard.xml",
        "wizards/hr_payroll_edit_payslip_lines_wizard_views.xml",
        "data/mail_template_data.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "ptplus_payroll/static/src/scss/single_report.scss",
            "ptplus_payroll/static/src/**/*.js",
        ]
    },
    "demo": [],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "external_dependencies": {"python": ["unidecode"]},
}
